### ISSUE TITLE
Publish new website

### ISSUE THREAD

**Issue by angeloashmore** [rom-rb/rom-rb.org#132]
The new website has not been published yet. Are there any outstanding tasks to be completed before updating it?

**Comment by solnic** [comment]
Apologies for this massive delay. dry-rb gems have been taking a lot of my time in the past few months and I couldn't finalize things on rom-rb side. We'll publish the new website along with the new release, I hoped to get it done by the end of June but it turned out to be impossible, so...hopefully July.

The only blocker we have for the website is updating content (updated docs, new guides, maybe some tutorials).

**Comment by solnic** [comment]
@angeloashmore hey, we're gonna publish the site this Wednesday. I pushed it to next.rom-rb.org for now as I'm still updating content :)

**Comment by angeloashmore** [comment]
That's awesome! Let me know if you need help. I won't be much help writing documentation, but I can implement any styling or structural changes.

**Comment by solnic** [comment]
@angeloashmore actually...I could use some help with improving spacing and header styles in /learn. I tweaked it a little so that we display a `:title » :chapter` at the top by default, but I feel like letters are too small and spacing between the header and first paragraph is too small too.

**Comment by solnic** [comment]
OK we managed to apply these tweaks :) It's published now...thank you once again for your help :)
