### ISSUE TITLE
Feedback on ROM - Status

### ISSUE THREAD

**Issue by venriq** [rom-rb/rom-rb.org#305]
Hi! I noticed that `rom-mongo` hasn't changed in the last three years and it's using the mongo driver gem `v2.2`. Is this because no one is supporting it or because no major changes are required?
I'm not sure if I'll have enough time but I could collaborate and update the versions.

**Comment by solnic** [comment]
@venriq hey :) this adapter has never reached production quality simply because there was nobody who wanted to use it AND had the time to work on it. I believe just bumping driver versions won't be enough though. It's missing many features and it still relies on `origin` which was merged to `mongoid` project, and we don't want to depend on the whole mongoid probably. Anyhow, it is not maintained and definitely needs help from people who use MongoDB.
