### ISSUE TITLE
In ROM Rails tutorial, don't use the ambiguous term "tasks"

### ISSUE THREAD

**Issue by postmodern** [rom-rb/rom-rb.org#32]
Was just reading the [ROM Rails tutorial](http://rom-rb.org/tutorials/rails/getting-started/) and was confused by the term `:tasks`. Task can refer to rake/make tasks or batch tasks. I suggest changing all instances of `:tasks` to something like `:todos`.

**Comment by maetl** [comment]
In a production app, particularly with a more intricate relational model, I would almost certainly use the term `tasks`, as it is unambiguous in the specific context of the model. But a tutorial is a different context—readability and understandability at a glance is extremely important.

I notice the cannonical Backbone model uses `todo` rather than `task`: http://backbonejs.org/docs/todos.html

`item` might also be less confusing.

**Comment by solnic** [comment]
Sorry, I missed that issue - I don't have an opinion, as in both work for me :) Feel free to rename. FWIW we also use user/task combo in the source code of ROM and its test suites. I'm fine with a mass-rename, really.

**Comment by maetl** [comment]
I’m okay with tasks for the time being. As long as the text is explicit about the meaning in the context of a todo list.

Will leave this open until the new tutorial lands and 0.6 is released—we can get a few people to read it, and see if it’s still confusing.

**Comment by carlisia** [comment]
@solnic, @maetl I recently read the tutorial and did not find the term `task` confusing at all. Perhaps this issue could be closed.

**Comment by solnic** [comment]
Yes I think we should close it. We haven't heard any complaints about this name except this one.
